### ISSUE TITLE
Can't build the docker images missing files (gisquick-dev.tar.gz, gisquick)

### ISSUE THREAD

**Issue by maureenvdr** [gislab-npo/gisquick#51]
Hi,

I can't seem to build the docker images and run them on windows. the dockerfiles are referencing folders/files that are not in the repository. for example gisquick-dev.tar.gz, gisquick.
I am running things on a windows 10 machine in docker version 18.06.1-ce-win73.
Even after i tried some changes so the images would build i get:
![image](https://user-images.githubusercontent.com/13275724/48007422-dcd14600-e117-11e8-9300-dffd33b853fb.png)

Building **django** 
the build.sh has cp ../../server/dist/gisquick-dev.tar.gz tmp/ in it, but gisquick-dev.tar.gz is missing. Am I correct in thinking this is the entire server folder but compacted into tar and gz? If i do that and add this to the tmp folder image based on the dockerfile is  build. But then running with docker compose up I get 404 not found errors about the static files. It looks as tho the static files are a level deeper in a folder admin.

Building **nginx**
this failed on the line "COPY gisquick /etc/nginx/conf.d/gisquick/", there is no gisquick to copy, what is this suppose to do? I commented out this line and image builds, but running things i get the 404 errors

I tried building them individually with
_docker build django
docker build nginx
docker build qgis-server_ (the only one that builds without errors)

And i created a docker-compose.yml with build options
this is what i have so far:

```
version: "3"
services:
  qgisserver:
    build:
        context: ./qgis-server
    restart: always
    image: gisquick/qgis-server
    volumes:
      - ./_data/publish:/publish/:ro
    networks:
      - default      
    ports:
      - "9000:9000"

  django:
    build:
        context: ./django
    restart: always
    image: gisquick/django
    volumes:
      - ./_data/data/:/var/www/gisquick/data/
      - ./_data/media/:/var/www/qisquick/media/      
      - ./_data/static/:/var/www/qisquick/static/   
      - ./_data/publish:/publish/
    environment:
      - GUNICORN_WORKERS=2
      - GUNICORN_ERRORLOG=-
      - GUNICORN_ACCESSLOG=-
    networks:
      - default  
    depends_on:
      - qgisserver              
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - "8000:8000"        

  nginx:
    build:
        context: ./nginx
    restart: unless-stopped
    image: gisquick/nginx   
    volumes:
      - ./_data/etc/letsencrypt/:/etc/letsencrypt/
      - ./_data/var/www/certbot/:/var/www/certbot/
      - ./_data/data/:/var/www/gisquick/data/
      - ./_data/media/:/var/www/qisquick/media/      
      - ./_data/static/:/var/www/qisquick/static/   
      - ./_data/publish:/publish/
    networks:
      - default       
    ports:
      - "80:80"      
      - "443:443"
    environment:
      - NGINX_HOST=localhost.merkator.com
    depends_on:
      - qgisserver 
      - django        
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  data: {}
```
Pleas help me out , what am i missing, i want to integrate quickgis with an existing website and add the necessary parts in an existing nginx image, but before i can do that i want to get this as is working.
